Main/DMT.Web/ViewModels/GenerateOrderbooksIndexVM.cs
using DMT.DTO;
using System.Collections.Generic;

namespace DMT.Web.ViewModels
{
    public class GenerateOrderbooksIndexVM
    {
        public IEnumerable<OrderbookWeekDTO> OrderbookWeeks { get; private set; }
        public OrderbookPreviewsDTO OrderbookPreviews { get; private set; }

        public GenerateOrderbooksIndexVM(IEnumerable<OrderbookWeekDTO> orderbookWeeks,
                                         OrderbookPreviewsDTO orderbookPreviews)
        {
            OrderbookWeeks = orderbookWeeks;
            OrderbookPreviews = orderbookPreviews;
        }

        public GenerateOrderbooksIndexVM(GenerateOrderbooksIndexVM goiVM)
        {
            OrderbookWeeks = goiVM.OrderbookWeeks;
            OrderbookPreviews = goiVM.OrderbookPreviews;
        }
    }
}

Main/DMT.Web/Controllers/GenerateOrderbooksController.cs
using DMT.DTO;
using DMT.GeneratingOrderbooks.Service.Interfaces;
using DMT.SharedKernel;
using DMT.Web.ViewModels;
using System.Web.Mvc;

namespace DMT.Web.Controllers
{
    public class GenerateOrderbooksController : Controller
    {
        private readonly IGeneratingOrderbooksService _GeneratingOrderbookService;

        public GenerateOrderbooksController(IGeneratingOrderbooksService generatingOrderbooksService)
        {
            _GeneratingOrderbookService = generatingOrderbooksService;
        }

        public ActionResult Index()
        {
            var generateOrderbooksIndexVM = 
                new GenerateOrderbooksIndexVM(_GeneratingOrderbookService.GetOrderbookWeeks(),
                                              _GeneratingOrderbookService.GetOrderbookPreviews());
            return View(generateOrderbooksIndexVM);
        }

        public OrderbookDTO GetOrderbook(ulong id)
        {
            return (_GeneratingOrderbookService.GetOrderbook(id));
        }

        public ActionResult _OrderbookPreview(string orderbookWeek)
        {
            OrderbookPreviewsDTO orderbookPreviews =
                _GeneratingOrderbookService.GetOrderbookPreviews(orderbookWeek);
            return PartialView("_OrderbookPreview", orderbookPreviews);
        }

        public EmptyResult GenerateOrderbooks()
        {
            _GeneratingOrderbookService.GenerateOrderbooks(new DateTimeConfig());
            return new EmptyResult();
        }
    }
}

Main/DMT.Web/Controllers/ManagingNotificationsController.cs
using DMT.DTO;
using DMT.ManagingNotifications.Service.Interfaces;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DMT.Web.Controllers
{
    public class ManagingNotificationsController : Controller
    {
        private readonly IManagingNotificationsService _managingNotificationsService;
        
        public ManagingNotificationsController(IManagingNotificationsService managingNotificationsService)
        {
            _managingNotificationsService = managingNotificationsService;
        }
        
        public ActionResult GetNotifications()
        {
            IReadOnlyList<NotificationDTO> notifications =
                _managingNotificationsService.GetNotifications();
        
            return PartialView("_Notifications", notifications);
        }
    }
}

Main/DMT.Web/Views/GenerateOrderbooks/Index.cshtml
@model DMT.Web.ViewModels.GenerateOrderbooksIndexVM

@{
    ViewBag.friendlyController = "Generate Orderbooks";
    ViewBag.friendlyAction = "Index";
}

<div class="home-index">
    <div class="home-index-generateorderbooks">
        <button type="button" class="btn-collins" id="GenerateOrderbooksButton">Generate Orderbooks</button>
    </div>

    <div class="home-index-vieworderbooks">
        <div class="orderbookWeek-dropdown">
            <div class="dropdown-header">
                <h2>Orderbooks</h2>
            </div>
            <div class="dropdown-wrapper">
                <select id="OrderbookWeekSelectBox">
                    <option disabled selected hidden>Choose Week</option>
                    @foreach (var item in Model.OrderbookWeeks)
                    {
                        <option>@Html.DisplayFor(modelItem => item.OrderbookWeek)</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div id="OrderbookPreviewPartial" class="orderbookpreview-table">
            @{
                Html.RenderPartial("_OrderbookPreview", Model.OrderbookPreviews);
            }
        </div>
    </div>

    <div class="home-index-notifications">
        @{
            Html.RenderAction("GetNotifications", "ManagingNotifications");
        }
    </div>
</div>

<script src="~/Scripts/Plugins/jquery.selectric.js"></script>
<script>Window.urlReq = '@System.Web.Configuration.WebConfigurationManager.AppSettings["DomainName"]' + '/GenerateOrderbooks/';</script>
<script>
    $('#OrderbookWeekSelectBox').selectric({
        maxHeight: 200,
        onChange: function (e) {
            var value = $(this).val();
            $('#OrderbookPreviewPartial')
                .load('@Url.Action("_OrderbookPreview", "GenerateOrderbooks")/?orderbookWeek=' + value);
        }
    });

    $('#GenerateOrderbooksButton').on('click', function () {
        $.get(Window.urlReq + 'GenerateOrderbooks');
    });
</script>

Main/DMT.Web/Views/GenerateOrderbooks/_OrderbookPreview.cshtml
@model DMT.DTO.OrderbookPreviewsDTO

<table id="OrderbookPreviewTable" class="cell-border hover stripe" style="width: 100%;">
    <thead>
        <tr>
            <th style="width: 25%;">Date Generated</th>
            <th style="width: 20%;">Vendor Code</th>
            <th style="width: 55%;">Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderbookPreviewDTOs)
        {
            <tr id="@item.Id">
                <td>@Html.DisplayFor(modelItem => item.DateGenerated)</td>
                <td>@Html.DisplayFor(modelItem => item.VendorCode)</td>
                <td>@Html.DisplayFor(modelItem => item.Description)</td>
            </tr>
        }
    </tbody>
    <tfoot><tr><td></td><td></td><td></td></tr></tfoot>
</table>

<script src="https://cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js"></script>
<script>
    $(document).ready(function () {
        // -- DataTables sorting rules
        $.fn.dataTable.moment("dd/MM/YYYY HH:mm:ss");

        // -- DataTables initialisation
        var orderbookPreviewTable =
            $('#OrderbookPreviewTable').DataTable({
                paging: false,
                info: false,
                order: [
                    [0, "desc"]
                ],
                scrollY: "40rem",
                scrollCollapse: true,
                searching: false,
                columns: [
                    null,
                    null,
                    { orderable: false }
                ]
            });
    });
</script>

Main/DMT.Web/Views/Shared/DisplayTemplates/NotificationState.cshtml
@model DMT.SharedKernel.NotificationState
@{
    switch (Model)
    {
        case DMT.SharedKernel.NotificationState.Success:
            <i class="fas fa-check-circle"></i>
            break;
        case DMT.SharedKernel.NotificationState.Warning:
            <i class="fas fa-exclamation-triangle"></i>
            break;
        case DMT.SharedKernel.NotificationState.Error:
            <i class="fas fa-exclamation-circle"></i>
            break;
        case DMT.SharedKernel.NotificationState.Information:
            <i class="fas fa-info-circle"></i>
            break;
        default:
            <i class="fas fa-exclamation-triangle"></i>
            break;
    }
}

Main/DMT.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.friendlyAction - Delivery Management Tool</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/moment")

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
</head>
<body>
    <header>
        <a class="header-logo" href="@Url.Action("Index", "GenerateOrderbooks")">
            <img class="logo" src="~/Content/Images/Delivery Management Tool_White.png" />
        </a>
        <nav class="header-nav">
            <ul>
                <li><a href="#">Order Books</a></li>
            </ul>
        </nav>
        <div class="header-accent"></div>
    </header>

    <main>
        @RenderBody()
    </main>

    @RenderSection("scripts", required: false)
</body>
</html>

Main/DMT.Web/Views/Shared/_Notifications.cshtml
@model IEnumerable<DMT.DTO.NotificationDTO>

<h2 class="header-underline">Notifications</h2>
<table id="NotificationTable" class="cell-border compact hover stripe" style="width: 100%;">
    <thead>
        <tr>
            <th style="width: 15%;">
                @Html.DisplayNameFor(model => model.DateRaised)
            </th>
            <th style="width: 80%;">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th style="width: 5%; text-align: center;">
                @Html.DisplayNameFor(model => model.NotificationState)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.DateRaised)</td>
                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                <td style="text-align: center;">
                    @Html.DisplayFor(modelItem => item.NotificationState)
                </td>
            </tr>
        }
    </tbody>
    <tfoot><tr><td></td><td></td><td></td></tr></tfoot>
</table>

<script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
<script src="~/signalr/hubs"></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js"></script>
<script src="https://cdn.datatables.net/plug-ins/1.10.20/sorting/enum.js"></script>
<script>
    $(document).ready(function () {
        // -- SignalR notification event
        var hub = $.connection.notificationsUpdatedHub;

        hub.client.appendToNotificationsTable = function (dateRaised, description, state) {
            notificationTable.row.add([
                dateRaised,
                description,
                state
            ]).draw(false);
        };

        $.connection.hub.start();

        // -- DataTables sorting rules
        $.fn.dataTable.moment('dd/MM/YYYY HH:mm:ss');
        $.fn.dataTable.enum([
            '<i class="fas fa-exclamation-circle"></i>',
            '<i class="fas fa-exclamation-triangle"></i>',
            '<i class="fas fa-check-circle"></i>',
            '<i class="fas fa-info-circle"></i>']);

        // -- DataTables initialisation
        var notificationTable =
            $('#NotificationTable').DataTable({
                paging: false,
                info: false,
                order: [
                    [0, "desc"]
                ],
                scrollY: "16rem",
                scrollCollapse: true,
                searching: false,
                columns: [
                    null,
                    { orderable: false },
                    null
                ],
                createdRow: function (row, data, index) {
                    if (data[2] != null) {
                        $('td', row).eq(2).addClass('center');
                    }
                }
            });
    });
</script>